// Code generated by goctl. DO NOT EDIT.
package trial

import (
	"gitlab.intsig.net/textin-gateway/internal/apiserver/types/service"
)

type TrialRouteDef struct{
	ServiceID         int    `json:"service_id"`
}

type TrialRoute struct{
	ServiceID   int            `json:"service_id"`
	ServiceName string         `json:"service_name"`
    ApiSet      service.ApiSet `json:"api_set"`
    AppKey 	    string         `json:"app_key"`
    AppSecret   string         `json:"app_secret"`
}

type TrialService struct {
	ID    int    `json:"id"`
	Name  string `json:"name"`
}

type TrialServiceList struct {
	Items []TrialService `json:"items"`
	Count uint64 `json:"count"`
}

type ListReq struct {
	Name  	string `form:"name"`                                   //引擎搜索关键字
	Page 		int    `form:"page"`  //页数
	PageSize 	int    `form:"page_size"` //页大小
}

type SchemaValidate struct {
	Json 		string    `json:"json"`
	Schema 		string    `json:"schema"`
}

type ValidateResult struct {
	Valid 		 	 bool 		   `json:"valid"`
	SchemaErrors 	 []interface{} `json:"schema_errors"`
	ValidationErrors []interface{} `json:"validation_errors"`
	SchemaParseError interface{}   `json:"schema_parse_error"`
	JSONParseError 	 interface{}   `json:"json_parse_error"`
}
