// Code generated by goctl. DO NOT EDIT.
package service

import (
	"gitlab.intsig.net/textin-gateway/internal/apiserver/handler/service"
	"gitlab.intsig.net/textin-gateway/internal/apiserver/middleware"
	"gitlab.intsig.net/textin-gateway/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterProductRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/gateway/v1")
	g.Use(middleware.AuthMiddleware)
	g.POST("/services", service.CreateServiceHandle(svcCtx))
	g.GET("/services/:id", service.GetServiceHandle(svcCtx))
	g.POST("/services/:id/update", service.UpdateServiceHandle(svcCtx))
	g.POST("/services/:id/delete", service.DeleteServiceHandle(svcCtx))
	g.GET("/services", service.ListServiceHandle(svcCtx))

}
