// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAccessLog = "access_log"

// AccessLog mapped from table <access_log>
type AccessLog struct {
	ID                 int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	RouteID            string  `gorm:"column:route_id;not null" json:"route_id"`
	RequestID          string  `gorm:"column:request_id;not null" json:"request_id"`
	ClientAddr         string  `gorm:"column:client_addr;not null" json:"client_addr"`
	IsoTime            string  `gorm:"column:iso_time;not null" json:"iso_time"`
	Timestamp          int64   `gorm:"column:timestamp;not null" json:"timestamp"`
	Datestamp          int64   `gorm:"column:datestamp;not null" json:"datestamp"`
	Minutestamp        int64   `gorm:"column:minutestamp;not null" json:"minutestamp"`
	Hourstamp          int64   `gorm:"column:hourstamp;not null" json:"hourstamp"`
	Weeklystamp        int64   `gorm:"column:weeklystamp;not null" json:"weeklystamp"`
	Monthstamp         int64   `gorm:"column:monthstamp;not null" json:"monthstamp"`
	Yearstamp          int64   `gorm:"column:yearstamp;not null" json:"yearstamp"`
	TimeCost           float64 `gorm:"column:time_cost;not null" json:"time_cost"`
	RequestLength      int32   `gorm:"column:request_length;not null" json:"request_length"`
	Connection         string  `gorm:"column:connection;not null" json:"connection"`
	ConnectionRequests string  `gorm:"column:connection_requests;not null;default:''" json:"connection_requests"`
	URI                string  `gorm:"column:uri;not null" json:"uri"`
	OriRequest         string  `gorm:"column:ori_request;not null" json:"ori_request"`
	QueryString        *string `gorm:"column:query_string;default:''" json:"query_string"`
	Status             int32   `gorm:"column:status;not null" json:"status"`
	BytesSent          int32   `gorm:"column:bytes_sent;not null" json:"bytes_sent"`
	Referer            *string `gorm:"column:referer;default:''" json:"referer"`
	UserAgent          string  `gorm:"column:user_agent;not null" json:"user_agent"`
	ForwardedFor       *string `gorm:"column:forwarded_for;default:''" json:"forwarded_for"`
	Host               *string `gorm:"column:host;default:''" json:"host"`
	Node               *string `gorm:"column:node;default:''" json:"node"`
	Upstream           string  `gorm:"column:upstream;not null;default:''" json:"upstream"`
}

// TableName AccessLog's table name
func (*AccessLog) TableName() string {
	return TableNameAccessLog
}
