// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApisixUpstream = "apisix_upstream"

// ApisixUpstream mapped from table <apisix_upstream>
type ApisixUpstream struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StreamID    string    `gorm:"column:stream_id;not null" json:"stream_id"`
	Content     string    `gorm:"column:content;not null" json:"content"`
	ContentYaml string    `gorm:"column:content_yaml;not null" json:"content_yaml"`
	Type        int16     `gorm:"column:type;not null" json:"type"`
	CreateAt    time.Time `gorm:"column:create_at;not null;default:CURRENT_TIMESTAMP" json:"create_at"`
	UpdateAt    time.Time `gorm:"column:update_at;not null;default:CURRENT_TIMESTAMP" json:"update_at"`
}

// TableName ApisixUpstream's table name
func (*ApisixUpstream) TableName() string {
	return TableNameApisixUpstream
}
