// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApplication = "application"

// Application mapped from table <application>
type Application struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	ChannelID      int32     `gorm:"column:channel_id;not null" json:"channel_id"`
	ServiceID      int32     `gorm:"column:service_id;not null" json:"service_id"`
	RouteID        string    `gorm:"column:route_id;not null" json:"route_id"`
	Status         int32     `gorm:"column:status;not null" json:"status"`
	CreatorID      *int32    `gorm:"column:creator_id" json:"creator_id"`
	LastEditorID   *int32    `gorm:"column:last_editor_id" json:"last_editor_id"`
	Abandoned      bool      `gorm:"column:abandoned;not null" json:"abandoned"`
	DelUniqueKey   int32     `gorm:"column:del_unique_key;not null" json:"del_unique_key"`
	Ctime          time.Time `gorm:"column:ctime;not null;default:CURRENT_TIMESTAMP" json:"ctime"`
	LastUpdateTime time.Time `gorm:"column:last_update_time;not null;default:CURRENT_TIMESTAMP" json:"last_update_time"`
}

// TableName Application's table name
func (*Application) TableName() string {
	return TableNameApplication
}
