// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChannel = "channel"

// Channel mapped from table <channel>
type Channel struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	CreatorID      int32     `gorm:"column:creator_id;not null" json:"creator_id"`
	LastEditorID   int32     `gorm:"column:last_editor_id;not null" json:"last_editor_id"`
	Abandoned      bool      `gorm:"column:abandoned;not null" json:"abandoned"`
	DelUniqueKey   *int32    `gorm:"column:del_unique_key" json:"del_unique_key"`
	Ctime          time.Time `gorm:"column:ctime;not null;default:CURRENT_TIMESTAMP" json:"ctime"`
	LastUpdateTime time.Time `gorm:"column:last_update_time;not null;default:CURRENT_TIMESTAMP" json:"last_update_time"`
}

// TableName Channel's table name
func (*Channel) TableName() string {
	return TableNameChannel
}
