// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameConfig = "config"

// Config mapped from table <config>
type Config struct {
	ID   *int32  `gorm:"column:id" json:"id"`
	Name *string `gorm:"column:name" json:"name"`
	Logo *string `gorm:"column:logo" json:"logo"`
}

// TableName Config's table name
func (*Config) TableName() string {
	return TableNameConfig
}
