// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameOptlog = "optlogs"

// Optlog mapped from table <optlogs>
type Optlog struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Operation    string    `gorm:"column:operation;not null" json:"operation"`
	Resource     *string   `gorm:"column:resource" json:"resource"`
	ResourceType *string   `gorm:"column:resource_type" json:"resource_type"`
	UserID       int32     `gorm:"column:user_id;not null" json:"user_id"`
	ReqBody      string    `gorm:"column:req_body;not null" json:"req_body"`
	OptTime      time.Time `gorm:"column:opt_time;not null;default:CURRENT_TIMESTAMP" json:"opt_time"`
}

// TableName Optlog's table name
func (*Optlog) TableName() string {
	return TableNameOptlog
}
