// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameService = "service"

// Service mapped from table <service>
type Service struct {
	ID             int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	UpstreamID     string    `gorm:"column:upstream_id;not null" json:"upstream_id"`
	APISet         JSON      `gorm:"column:api_set;not null" json:"api_set"`
	CreatorID      *int32    `gorm:"column:creator_id" json:"creator_id"`
	LastEditorID   *int32    `gorm:"column:last_editor_id" json:"last_editor_id"`
	Abandoned      bool      `gorm:"column:abandoned;not null" json:"abandoned"`
	DocumentID     int32     `gorm:"column:document_id;not null" json:"document_id"`
	ServiceType    string    `gorm:"column:service_type;not null;default:others" json:"service_type"`
	DelUniqueKey   *int32    `gorm:"column:del_unique_key" json:"del_unique_key"`
	Ctime          time.Time `gorm:"column:ctime;not null;default:CURRENT_TIMESTAMP" json:"ctime"`
	LastUpdateTime time.Time `gorm:"column:last_update_time;not null;default:CURRENT_TIMESTAMP" json:"last_update_time"`
}

// TableName Service's table name
func (*Service) TableName() string {
	return TableNameService
}
