// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVersion = "versions"

// Version mapped from table <versions>
type Version struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ServiceID   int32  `gorm:"column:service_id;not null" json:"service_id"`
	Version     string `gorm:"column:version;not null" json:"version"`
	UpstreamMap JSON   `gorm:"column:upstream_map;not null;default:'[]'::jsonb" json:"upstream_map"`
}

// TableName Version's table name
func (*Version) TableName() string {
	return TableNameVersion
}
