// Code generated by goctl. DO NOT EDIT.
package channel

import (
	"gitlab.intsig.net/textin-gateway/internal/apiserver/handler/channel"
	"gitlab.intsig.net/textin-gateway/internal/apiserver/middleware"
	"gitlab.intsig.net/textin-gateway/internal/apiserver/svc"

	"github.com/gin-gonic/gin"
)

func RegisterChannelRoute(e *gin.Engine, svcCtx *svc.ServiceContext) {
	g := e.Group("/gateway/v1")
	g.Use(middleware.AuthMiddleware)
	g.POST("/channels", channel.CreateChannelHandle(svcCtx))
	g.GET("/channels/:id", channel.GetChannelHandle(svcCtx))
	g.POST("/channels/:id/update", channel.UpdateChannelHandle(svcCtx))
	g.POST("/channels/:id/delete", channel.DeleteChannelHandle(svcCtx))
	g.GET("/channels", channel.ListChannelHandle(svcCtx))

}
